/**
 * SodaRender
 * light Tml render engine
 * copyright @ Tencent AlloyTeam
 * License under MIT License
 * @author dorsywang
 * @email 314416946@qq.com
 * @blog http://www.dorsywang.com
 * @TeamBlog http://www.alloyteam.com
 */
(function(){var e=/\{\{([^\}]*)\}\}/g,t=function(e,n){var r=n.indexOf(".");if(r>-1){var i=n.substr(0,r);return n=n.substr(r+1),e[i]?t(e[i],n):""}return e[n]||""},n=function(e){},r=/[a-zA-Z_\$]+[\w\$]*/g,i=/"[^"]*"/g,s=/\d+|\d*\.\d+/g,o=/[a-zA-Z_\$]+[\w\$]*(?:[a-zA-Z_\$]+[\w\$]*|\.|\s)*/g,u=function(e){var e=e.split("|"),n=e[0]||"",r=e.slice(1);n=n.replace(o,function(e){return"getValue(scope,'"+e.trim()+"')"});var i=function(){var e=r.shift();if(!e)return;var e=e.split(":"),t=e.slice(1)||[],s=e[0]||"";l[s]&&(t.unshift(n),t=t.join(","),n="sodaFilterMap['"+s+"']("+t+")"),i()};i(),console.log(n);var s=(new Function("getValue","sodaFilterMap","return function sodaExp(scope){ return "+n+"}"))(t,l);return s},a=function(t,n){[].map.call([].slice.call(t.childNodes,[]),function(t){t.nodeType===3&&(t.nodeValue=t.nodeValue.replace(e,function(e,t){return u(t)(n)})),t.attributes&&(/in/.test(t.getAttribute("soda-repeat")||"")?f["soda-repeat"].link(n,t,t.attributes):([].map.call(t.attributes,function(r){if(/^soda-/.test(r.name)){if(f[r.name]){var i=f[r.name];i.link(n,t,t.attributes)}}else r.value=r.value.replace(e,function(e,t){return u(t)(n)})}),a(t,n)))})},f={},l={},c=function(e,t){f["soda-"+e]=t()},h=function(e,t){l[e]=t};h("date",function(e,t){return t}),c("repeat",function(){return{compile:function(e,t,n){},link:function(n,r,i){var s=r.getAttribute("soda-repeat"),o,l;if(!/in/.test(s))return;s=s.split("in"),o=s[0].trim(),l=s[1].trim();var c=t(n,l),h=r;for(var p=0;p<c.length;p++){var d=r.cloneNode(),v={$index:p};v[o]=c[p],v.__proto__=n,d.innerHTML=r.innerHTML,[].map.call(d.attributes,function(t){if(d.getAttribute("removed")==="removed")return;if(t.name.trim()!=="soda-repeat")if(/^soda-/.test(t.name)){if(f[t.name]){var n=f[t.name];n.link(v,d,d.attributes)}}else t.value=t.value.replace(e,function(e,t){return u(t)(v)})}),d.getAttribute("removed")!=="removed"&&(a(d,v),r.parentNode.insertBefore(d,h.nextSibling),h=d)}r.parentNode.removeChild(r)}}}),c("if",function(){return{link:function(e,t,n){var r=t.getAttribute("soda-if"),i=u(r);console.log(i),i(e)||(t.setAttribute("removed","removed"),t.parentNode&&t.parentNode.removeChild(t))}}});var p=function(e,t){var n=document.createElement("div");n.innerHTML=e,a(n,t),console.log(n),console.log(n.innerHTML);var r=document.createDocumentFragment();r.innerHTML=n.innerHTML;var i;while(i=n.childNodes[0])r.appendChild(i);return r};window.sodaRender=p,window.sodaFilter=h})()
