/**
 * SodaRender
 * light Tml render engine
 * copyright @ Tencent AlloyTeam
 * License under MIT License
 * @author dorsywang
 * @email 314416946@qq.com
 * @blog http://www.dorsywang.com
 * @TeamBlog http://www.alloyteam.com
 */
(function(){var e=/\{\{([^\}]*)\}\}/g;Object.prototype.__getValue=function(e){return this[e]||""};var t=function(e,n){var r=n.indexOf(".");if(r>-1){var i=n.substr(0,r);return n=n.substr(r+1),e[i]?t(e[i],n):""}return e[n]||""},n=function(e){},r=/[a-zA-Z_\$]+[\w\$]*/g,i=/"[^"]*"/g,s=/\d+|\d*\.\d+/g,o=/[a-zA-Z_\$]+[\w\$]*(?:\s*\.\s*(?:[a-zA-Z_\$]+[\w\$]*|\d+))*/g,u=/\[([^\[\]]*)\]/g,a=/\.([a-zA-Z_\$]+[\w\$]*)/g,f=/[^\.|]([a-zA-Z_\$]+[\w\$]*)/g,l=function(e,n){var e=e.split("|"),r=e[0]||"",i=e.slice(1);while(u.test(r))u.lastIndex=0,r=r.replace(u,function(e,t){return"."+l(t,n)});r=r.replace(o,function(e){return"getValue(scope,'"+e.trim()+"')"});var s=function(){var e=i.shift();if(!e)return;var e=e.split(":"),t=e.slice(1)||[],n=e[0]||"";p[n]&&(t.unshift(r),t=t.join(","),r="sodaFilterMap['"+n+"']("+t+")"),s()};s();var a=(new Function("getValue","sodaFilterMap","return function sodaExp(scope){ return "+r+"}"))(t,p);return a(n)},c=function(t,n){[].map.call([].slice.call(t.childNodes,[]),function(t){t.nodeType===3&&(t.nodeValue=t.nodeValue.replace(e,function(e,t){return l(t,n)})),t.attributes&&(/in/.test(t.getAttribute("soda-repeat")||"")?h["soda-repeat"].link(n,t,t.attributes):([].map.call(t.attributes,function(r){if(/^soda-/.test(r.name)){if(h[r.name]){var i=h[r.name];i.link(n,t,t.attributes)}}else r.value=r.value.replace(e,function(e,t){return l(t,n)})}),c(t,n)))})},h={},p={},d=function(e,t){h["soda-"+e]=t()},v=function(e,t){p[e]=t};v("date",function(e,t){return t}),d("repeat",function(){return{compile:function(e,t,n){},link:function(n,r,i){var s=r.getAttribute("soda-repeat"),o,u;if(!/in/.test(s))return;s=s.split("in"),o=s[0].trim(),u=s[1].trim();var a=t(n,u),f=r;for(var p=0;p<a.length;p++){var d=r.cloneNode(),v={$index:p};v[o]=a[p],v.__proto__=n,d.innerHTML=r.innerHTML,[].map.call(d.attributes,function(t){if(d.getAttribute("removed")==="removed")return;if(t.name.trim()!=="soda-repeat")if(/^soda-/.test(t.name)){if(h[t.name]){var n=h[t.name];n.link(v,d,d.attributes)}}else t.value=t.value.replace(e,function(e,t){return l(t,v)})}),d.getAttribute("removed")!=="removed"&&(c(d,v),r.parentNode.insertBefore(d,f.nextSibling),f=d)}r.parentNode.removeChild(r)}}}),d("if",function(){return{link:function(e,t,n){var r=t.getAttribute("soda-if"),i=l(r,e);i||(t.setAttribute("removed","removed"),t.parentNode&&t.parentNode.removeChild(t))}}});var m=function(e,t){var n=document.createElement("div");n.innerHTML=e,c(n,t);var r=document.createDocumentFragment();r.innerHTML=n.innerHTML;var i;while(i=n.childNodes[0])r.appendChild(i);return r},g=function(e,t){};window.sodaRender=m,window.sodaFilter=v})()
