/**
 * SodaRender
 * light Tml render engine
 * copyright @ Tencent AlloyTeam
 * License under MIT License
 * @author dorsywang
 * @email 314416946@qq.com
 * @blog http://www.dorsywang.com
 * @TeamBlog http://www.alloyteam.com
 */
(function(){var e=function(e){return e=e.replace(/&/g,"&amp;"),e=e.replace(/>/g,"&gt;"),e=e.replace(/</g,"&lt;"),e=e.replace(/"/g,"&quot;"),e=e.replace(/'/g,"&#39;"),e},t=function(e){if(!e)return"";var t=/\&#(\d+);/g;return e.replace(t,function(e,t){return String.fromCharCode(t)})},n=function(e){var t;return t=e,t+="",t=t.replace(/&/g,"&amp;"),t=t.replace(/>/g,"&gt;"),t=t.replace(/</g,"&lt;"),t=t.replace(/"/g,"&quot;"),t=t.replace(/'/g,"&#39;"),t=t.replace(/=/g,"&#61;"),t=t.replace(/`/g,"&#96;"),t},r=function(t,r){var i,s="";for(var o in r)s+="var "+o+" = data."+o+";";t=t.replace(/\s+/g," "),t=t.replace(/'/g,"\\'"),t=t.replace(/<!--\?/g,"<?"),t=t.replace(/\?-->/g,"?>"),t=s+"var __result = ''; ?>"+t+"<?",t+=" return __result;",t=t.replace(/<\?=([^\?]+)\?>/g,"' + $1 + '").replace(/<\?\+([^\?]+)\?>/g,"' + _SodaTool.encodeHtmlSimple($1) + '").replace(/<\?-([^\?]+)\?>/g,"' + _SodaTool.encodeAttr($1) + '").replace(/<\?/gi,"';").replace(/\?>/g,"__result += '");var u=new Function("data","_SodaTool",t);return i=u(r,{encodeHtmlSimple:e,encodeAttr:n}),i},i={},s=function(e,t,n){var s=document.getElementById(e);s||(s=document.querySelector(".soda_"+e),console.log(s));if(!s)return;var o=s.innerHTML,u=r(o,t);i[e]||(i[e]=[]);if(!n)for(var a=0;a<i[e].length;a++){var f=i[e][a];f.parentNode.removeChild(f)}i[e]=[];var l=document.createElement("div");l.innerHTML=u;var c=l.childNodes;while(c.length>0)i[e].push(c[0]),s.parentNode.insertBefore(c[0],s)},o=function(e,t,n){if(!(this instanceof o))return(new o(e,t,n)).render();this.id=e,this.data=t,this.isAppend=n,this.render()};o.prototype={update:function(e){var t=e||this.data;return t&&s(this.id,t),this},render:function(e,t){var n=e||this.data,r=t||this.isAppend;return n&&s(this.id,n,r),this}},o.render=function(e,t,n){return new o(e,t,n)},window.sodarender=window.SodaRender=window.$SR=o,window.addEventListener("DOMContentLoaded",function(){var e=document.getElementsByTagName("*");Array.prototype.map.call(e,function(e,t){var n;if(n=e.getAttribute("soda-model")){var r=e.innerHTML,i=document.createElement("script");i.type="text/soda",i.innerHTML=r,i.id=n,e.innerHTML="",e.appendChild(i)}})})})()
